#!/bin/bash --login

# set the number of nodes and processes per node. We are running one process on a single node
#PBS -l select=64
# for jobs needing 128Gb per node
####PBS -l select=1:bigmem=true

#PBS -l walltime=00:30:00

#PBS -A e555

# set name of job
#PBS -N QuEST

module swap PrgEnv-cray PrgEnv-intel

cd $PBS_O_WORKDIR

NUM_QUBITS=33
EXE=demo
export KMP_AFFINITY=disabled
export OMP_NUM_THREADS=24

make clean
make

aprun -n 64 -d 24 -cc numa_node ./$EXE $NUM_QUBITS
