#!/bin/bash --login

# set the number of nodes and processes per node. We are running one process on a single node
#PBS -l select=16
# for jobs needing 128Gb per node
####PBS -l select=1:bigmem=true

#PBS -l walltime=00:30:00
#PBS -A INSERT_PROJECT_CODE

# set name of job
#PBS -N QuEST

module swap PrgEnv-cray PrgEnv-intel

cd $PBS_O_WORKDIR

NUM_QUBITS=34
EXE=demo
export KMP_AFFINITY=disabled
export OMP_NUM_THREADS=16

make clean
make

aprun -n 16 -d 16 -cc numa_node ./$EXE $NUM_QUBITS
