#!/bin/bash --login

# set the number of nodes and processes per node. We are running one process on a single node
#PBS -l select=1
# for jobs needing 128Gb per node
####PBS -l select=1:bigmem=true

#PBS -l walltime=00:20:00

#PBS -A e555

# set name of job
#PBS -N QuEST

module swap PrgEnv-cray PrgEnv-intel

cd $PBS_O_WORKDIR

NUM_QUBITS=30
EXE=demo
export KMP_AFFINITY=disabled
export OMP_NUM_THREADS=12

make clean
make

aprun -n 2 -d 12 -cc 0,x,1-11:12,x,13-23 ./$EXE $NUM_QUBITS
