#!/bin/bash --login

# set the number of nodes and processes per node. We are running one process on a single node
#PBS -l select=1:ncpus=24:ompthreads=24:mem=50gb

#PBS -l walltime=00:10:00

# set name of job
#PBS -N QuEST

module purge
module load intel-suite mpi
module list

NUM_QUBITS=29
EXE=demo

export OMP_PROC_BIND=true
export OMP_NUM_THREADS=24


$PBS_O_WORKDIR/demo $NUM_QUBITS

cp $TMPDIR/TIMINGROTATE_* $PBS_O_WORKDIR/
