#!/bin/bash --login

# set the number of nodes and processes per node. We are running one process on a single node
#PBS -l select=64:ncpus=24:ompthreads=24:mem=50gb

#PBS -l walltime=01:30:00

# set name of job
#PBS -N QuEST

module purge
module load intel-suite mpi/intel-2018
module list

NUM_QUBITS=35
EXE=demo

export OMP_NUM_THREADS=24


mpiexec $PBS_O_WORKDIR/demo $NUM_QUBITS

cp $TMPDIR/TIMINGROTATE_* $PBS_O_WORKDIR/
